namespace BillsApi.Models;

/// <summary>
/// Represents a bill in the MonthlyBillCalculator application.
/// </summary>
public class Bill
{
    /// <summary>
    /// Unique identifier (auto-generated by API).
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// The ID of the user who owns this bill.
    /// </summary>
    public required string UserId { get; set; }

    /// <summary>
    /// Name/description of the bill (e.g., "Electricity", "Gas", "Water").
    /// </summary>
    public required string BillName { get; set; }

    /// <summary>
    /// The full bill amount.
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Date of the bill (ISO 8601 format).
    /// </summary>
    public DateTime Date { get; set; }

    /// <summary>
    /// Amount over the minimum threshold (user-entered value).
    /// </summary>
    public decimal AmountOverMinimum { get; set; }

    /// <summary>
    /// Indicates whether the bill has been paid.
    /// </summary>
    public bool IsPaid { get; set; }

    /// <summary>
    /// Date when the bill was paid (null if not paid).
    /// </summary>
    public DateTime? PaidDate { get; set; }
}

