@BillsApi_HostAddress = https://bills.dukesducks.ca/billsapi
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjU2M2JjMDJlLTQwMjgtNGEyNC04ZjI3LTg0M2YxNDgzMzMxZiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJNYXYiLCJleHAiOjE3NzA1NzUyOTEsImlzcyI6IkJpbGxzQXBpIiwiYXVkIjoiQmlsbHNBcGlVc2VycyJ9.d7cTzC6R21kxFBCgNxCb6AlQoIame40_n8aXo6CG4GI
@refreshToken = C6rqUcpR3taRnxD6hscCFxKmO3Wuf/w4pzx5oCwpu/CWOqsl6B5nsiRNd7UYv8fwgSRoCnWZgdC1ZRZKx/NaYw==

### Register a new user
POST {{BillsApi_HostAddress}}/auth/register
Content-Type: application/json

{
  "username": "Mav",
  "password": "Password123!",
  "email": "maverick24@sfosquad.com"
}

### Login to get JWT token
POST {{BillsApi_HostAddress}}/auth/login
Content-Type: application/json

{
  "username": "Mav",
  "password": "Password123!"
}

### Get all bills (requires authentication)
GET {{BillsApi_HostAddress}}/bills
Accept: application/json
Authorization: Bearer {{token}}

### Get single bill by ID (requires authentication)
GET {{BillsApi_HostAddress}}/bills/2
Accept: application/json
Authorization: Bearer {{token}}

### Create a new bill (requires authentication)
POST {{BillsApi_HostAddress}}/bills
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "billName": "Maverick",
  "amount": 150.00,
  "date": "2026-01-14T00:00:00",
  "amountOverMinimum": 20.00,
  "isPaid": false,
  "paidDate": null
}

### Update a bill (requires authentication)
PUT {{BillsApi_HostAddress}}/bills/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "billName": "Update",
  "amount": 135.50,
  "date": "2024-01-15T00:00:00",
  "amountOverMinimum": 30.50,
  "isPaid": true,
  "paidDate": "2024-01-15T00:00:00"
}

### Delete a bill (requires authentication)
DELETE {{BillsApi_HostAddress}}/bills/7
Authorization: Bearer {{token}}

### Refresh JWT Token
POST {{BillsApi_HostAddress}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}


### Forgot password (send reset email)
POST {{BillsApi_HostAddress}}/auth/forgot-password
Content-Type: application/json

{
  "email": "maverick24@sfosquad.com"
}


### Reset password (use token from email)
POST {{BillsApi_HostAddress}}/auth/reset-password
Content-Type: application/json

{
  "userId": "5d9ab2d6-176e-468e-8ced-a3d792e3fd13",
  "token": "4w6P1jRY2ckzveDidDihzR+hxpQjn+IghSuNpAEVJeI=",
  "newPassword": "NewPassword123!"
}

### Delete account and all associated bills (requires authentication)
DELETE {{BillsApi_HostAddress}}/auth/account
Authorization: Bearer {{token}}






